#!/bin/bash
# -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# vim: et sts=4 sw=4

# Copyright © 2023-2024 Igalia S.L.
# Copyright © 2023 Collabora Ltd.
# Copyright © 2023-2024 Valve Corporation.
#
# SPDX-License-Identifier: LGPL-2.1-or-later

set -euo pipefail

SWAPFILE=${1:-}

# exit_with_warning() uses exit-code=0 instead of some other
# error-indicating code because, while it does not remove the file
# (doesn't perform its main function/purpose), it is actually OK from
# the theoretical point of view.  This is because the 'swapfile' is
# not deemed to be the "default" one created by an older SteamOS
# release.
#
# And from point of view of the associated .service invoking this
# script, it needs to use exit-code=0 to not raise the alarm and mark
# the services as failed in every OS restart when the .service is
# invoked.  If another exit-code is used (e.g. 201) to denote an
# error, the .service file has to be modified to match (i.e., adding
# it as an acceptable exit value: "SuccessExitStatus=0 201").
exit_with_warning()  { echo >&2 "Warning: $@"; exit 0; }
usage()              { echo >&2 "Usage: $(basename "$0") FILE"; exit 1; }

[ "$SWAPFILE" ] || usage

if [ ! -e "$SWAPFILE" ] ; then
    echo "File '$SWAPFILE' does not exist, nothing to remove"
    exit 0
fi

# The script might be run manually or the service calling could get
# restarted, while users might have enabled a swapfile by hand.  In
# either case, the swap is likely to be setup.
if grep -q "^$SWAPFILE " /proc/swaps; then
    exit_with_warning "'$SWAPFILE' actively used as swap, refusing to remove"
fi

if grep -q "$SWAPFILE" /etc/fstab &>/dev/null; then
    exit_with_warning "'$SWAPFILE' mentioned in '/etc/fstab', refusing to remove"
fi

if [ -L "$SWAPFILE" ] || [ ! -f "$SWAPFILE" ] ; then
    exit_with_warning "file '$SWAPFILE' not a regular file, refusing to remove"
fi

if ! file "$SWAPFILE" |& grep -q "^$SWAPFILE: Linux swap file,"; then
    exit_with_warning "file '$SWAPFILE' does not seem to be an actual swapfile (checked with 'file'), refusing to remove"
fi

if [[ $(stat -c '%s' "$SWAPFILE") -ne 1073741824 ]]; then
    exit_with_warning "file '$SWAPFILE' is not of the expected default size (1024MiB), refusing to remove"
fi

echo "All safety checks passed, removing swapfile '$SWAPFILE'"
rm -fv "$SWAPFILE"
