[Sleep]
AllowHibernation=yes
AllowSuspendThenHibernate=yes

HibernateDelaySec=6h

# Only count down hibernation timer when not on AC power
# This preserves battery while allowing indefinite suspend when plugged in
HibernateOnACPower=no
