[UPower]

# Holo: Set PercentageAction to 0.33 instead of the default 2.0 from upstream.
#
# This is very tight, but this task is managed by a combination of vpower and
# SteamUI that only starts when the battery charge dips below 0.5%, and gives a
# 10 second margin for SteamUI to close.  So we cannot use a number much higher
# than 0.33%, unless the percentages of the other mechanism is also raised.
#
# By changing to 0.33% instead of setting CriticalPowerAction=Ignore (as it was
# done in the past), this is a last attempt from UPower to shut down cleanly, if
# the expected mechanism failed.
PercentageAction=0.33
