#!/bin/bash
# -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# vim: et sts=4 sw=4

#  SPDX-License-Identifier: LGPL-2.1+
#
#  Copyright © 2020 Collabora Ltd.
#  Copyright © 2020 Valve Corporation.
#
#  This file is part of steamos-customizations.
#
#  steamos-customizations is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public License as
#  published by the Free Software Foundation; either version 2.1 of the License,
#  or (at your option) any later version.

exec kupdate-notifier /usr/lib/steamos/steamos-update-os-notifier.action 3600 --online-updates --offline-updates \
                      --tooltip-title "SteamOS Update Operating System Notifier" \
                      --tooltip-subtitle "SteamOS Update Operating System Notifier for the new systemtray specification"
